version: '3.8'

services:
  rocketchat:
    build:
      context: .
      dockerfile: Dockerfile
    image: custom-k12-chat:v1.0
    restart: always
    environment:
      - PORT=3000
      - ROOT_URL=http://localhost:3000
      - MONGO_URL=mongodb://mongodb:27017/rocketchat?replicaSet=rs0
      - MONGO_OPLOG_URL=mongodb://mongodb:27017/local?replicaSet=rs0
    depends_on:
      - mongodb
    ports:
      - "3000:3000"

  mongodb:
    image: bitnami/mongodb:5.0
    restart: always
    volumes:
      - mongodb_data:/bitnami/mongodb
    environment:
      - MONGODB_REPLICA_SET_MODE=primary
      - MONGODB_REPLICA_SET_NAME=rs0

volumes:
  mongodb_data:
